/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProgramandoComGradle;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
        Connection conn = DriverManager.getConnection (
                "jdbc:postgresql://" + "localhost" + ":" + "5432" + "/" + "luciene locadora", "postgres", "postgres");
   }
  }

